"""added users.is_human

Revision ID: 36fda561e22f
Revises: None
Create Date: 2015-03-21 02:32:57.989610

"""

# revision identifiers, used by Alembic.
revision = '36fda561e22f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_human', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_human')
    ### end Alembic commands ###
